### ISSUE TITLE
User get kicked

### ISSUE THREAD

**Issue by XaviFortes** [theusaf/kahoot-winner#6]
When using your website it seems that kahoot kicks the user using Kahoot Winner.

**Comment by theusaf** [comment]
Are you sure you are getting kicked? Usually this means that the host is kicking you themselves, maybe using Kahoot antibot.

Please provide screenshots if you can if this is not the case. 

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir

**Comment by theusaf** [comment]
To clarify, if you get kicked, a red message should appear at the top with something like `Session Ended (Kicked)`. If you are disconnected for a different reason, it may be because Google Recaptcha things you are a bot.
