### ISSUE TITLE
its blocked on my school internet

### ISSUE THREAD

**Issue by BTStudz** [theusaf/kahoot-winner#9]
can you pls add a deploy to heroku button in the description so i can make a new unblocked one?
thanks in advance

**Comment by theusaf** [comment]
This repo is not configured to work well on heroku, so adding that button won’t help. You can check the faq in the discord faq or kahoot.js.org/websites for alternative links.

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir
